# Generated by Django 5.1.7 on 2025-04-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_flashcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flashcard',
        ),
    ]
